/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Simple model to hold the query and response.
 * @export
 * @interface QueryResponse
 */
export interface QueryResponse {
  [key: string]: any | any;
  /**
   *
   * @type {string}
   * @memberof QueryResponse
   */
  prompt: string;
  /**
   *
   * @type {string}
   * @memberof QueryResponse
   */
  response: string;
}

/**
 * Check if a given object implements the QueryResponse interface.
 */
export function instanceOfQueryResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "prompt" in value;
  isInstance = isInstance && "response" in value;

  return isInstance;
}

export function QueryResponseFromJSON(json: any): QueryResponse {
  return QueryResponseFromJSONTyped(json, false);
}

export function QueryResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): QueryResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...json,
    prompt: json["prompt"],
    response: json["response"],
  };
}

export function QueryResponseToJSON(value?: QueryResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...value,
    prompt: value.prompt,
    response: value.response,
  };
}
