/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { QueryResponse } from "./QueryResponse";
import {
  QueryResponseFromJSON,
  QueryResponseFromJSONTyped,
  QueryResponseToJSON,
} from "./QueryResponse";

/**
 * Simple model to hold the response to an update request.
 * @export
 * @interface UpdateResponse
 */
export interface UpdateResponse {
  [key: string]: any | any;
  /**
   *
   * @type {string}
   * @memberof UpdateResponse
   */
  message: string;
  /**
   *
   * @type {QueryResponse}
   * @memberof UpdateResponse
   */
  query: QueryResponse;
}

/**
 * Check if a given object implements the UpdateResponse interface.
 */
export function instanceOfUpdateResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "message" in value;
  isInstance = isInstance && "query" in value;

  return isInstance;
}

export function UpdateResponseFromJSON(json: any): UpdateResponse {
  return UpdateResponseFromJSONTyped(json, false);
}

export function UpdateResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...json,
    message: json["message"],
    query: QueryResponseFromJSON(json["query"]),
  };
}

export function UpdateResponseToJSON(value?: UpdateResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...value,
    message: value.message,
    query: QueryResponseToJSON(value.query),
  };
}
